FROM python:3.13

WORKDIR /backend

# install python libraries
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy code into container
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

